version: '3.8'

services:

  redis:
    image: redis:7-alpine
    container_name: sentinel_redis
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: sentinel_backend
    environment:
      - DATABASE_URL=mongodb+srv://adamalok79_db_user:kondabot@cluster0.wjo1gru.mongodb.net/?appName=Cluster0
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=SUPER_SECRET_NEON_SENTINEL_SHIELD_KEY_2026
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_started

  web:
    build: ./web
    container_name: sentinel_web_app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: sentinel_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
      - backend

